project_id = "oeevjolpgqafqzvnviqs"

[functions.stellar-issue-tesouro]
verify_jwt = false

[functions.stellar-burn-tesouro]
verify_jwt = false

[functions.etherfuse-create-offramp]
verify_jwt = false

[functions.password-recovery-random]
verify_jwt = false

